### ISSUE TITLE
The image is not valid. Please check your image exists.

### ISSUE THREAD

**Issue by sri-wahyuni10** [violencedetector/realtime#4]
i have error for file estimator.py "The image is not valid. Please check your image exists."  i try this program in google colab, but when i running, can you help me? 
thanks

**Comment by violencedetector** [comment]
Hi, do you have the frames to be infered inside the /image folder?  Could you please describe the command line which gave you this error?

**Comment by sri-wahyuni10** [comment]
thanks, i got the solution.  that's true, I specified the wrong folder address. thanks you for have taken the time.
